-- Run once in Supabase SQL Editor before testing Agent violations.
-- This migration is additive and does not alter existing tables.

create table if not exists public.usage_violations (
    id bigint generated by default as identity primary key,
    lab_access_log_id bigint not null
        references public.lab_access_logs(id),
    program_usage_log_id bigint null
        references public.program_usage_logs(id),
    program_name varchar not null,
    detected_at timestamp without time zone not null default now(),
    reason text null,
    action_taken varchar not null default 'logout'
);

create index if not exists idx_usage_violations_session_id
    on public.usage_violations(lab_access_log_id);

create index if not exists idx_usage_violations_detected_at
    on public.usage_violations(detected_at);
