-- Register each Lab workstation once and derive its Lab assignment server-side.
-- Run after 010_database_cleanup.sql.

CREATE TABLE IF NOT EXISTS public.lab_devices (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id varchar(128) NOT NULL UNIQUE,
    lab_id integer NOT NULL REFERENCES public.labs(id),
    device_name varchar(255) NOT NULL,
    device_mac varchar(64),
    status varchar(32) NOT NULL DEFAULT 'active',
    agent_token_hash varchar(64) NOT NULL UNIQUE,
    agent_version varchar(64),
    last_seen_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT lab_devices_status_check
        CHECK (status IN ('active', 'maintenance', 'revoked'))
);

CREATE INDEX IF NOT EXISTS idx_lab_devices_lab_id
    ON public.lab_devices (lab_id);

CREATE INDEX IF NOT EXISTS idx_lab_devices_status
    ON public.lab_devices (status);

CREATE TABLE IF NOT EXISTS public.lab_device_enrollments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_id integer NOT NULL REFERENCES public.labs(id),
    token_hash varchar(64) NOT NULL UNIQUE,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    used_device_id varchar(128),
    created_by integer NOT NULL REFERENCES public.users(id),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lab_device_enrollments_expires_at
    ON public.lab_device_enrollments (expires_at);

CREATE INDEX IF NOT EXISTS idx_lab_device_enrollments_lab_id
    ON public.lab_device_enrollments (lab_id);

ALTER TABLE public.lab_access_logs
    ADD COLUMN IF NOT EXISTS lab_device_id integer
        REFERENCES public.lab_devices(id);

CREATE INDEX IF NOT EXISTS idx_lab_access_logs_lab_device_id
    ON public.lab_access_logs (lab_device_id);
