import { useEffect, useMemo, useState } from "react";
import { LanguageContext } from "./language-context.js";

const LANGUAGE_STORAGE_KEY = "smart-lab-language";

const messages = {
  th: {
    language: {
      switchTo: "English",
      current: "ภาษาไทย",
      aria: "เปลี่ยนภาษาเป็นภาษาอังกฤษ",
    },
    common: {
      labReserve: "จองห้อง Lab",
      reserved: "รายการจอง",
      history: "ประวัติการจอง",
      myTickets: "ตั๋วของฉัน",
      support: "ช่วยเหลือ",
      notifications: "การแจ้งเตือน",
      noNotifications: "ยังไม่มีการแจ้งเตือน",
      systemAdmin: "ผู้ดูแลระบบ",
      administrator: "ผู้ดูแลระบบ",
      profile: "โปรไฟล์",
      manageAccount: "จัดการบัญชี",
      guestUser: "ผู้ใช้ Guest",
      login: "เข้าสู่ระบบ",
      settings: "ตั้งค่า",
      logout: "ออกจากระบบ",
      search: "ค้นหา...",
      refresh: "รีเฟรชข้อมูล",
      save: "บันทึก",
      cancel: "ยกเลิก",
      close: "ปิด",
      edit: "แก้ไข",
      delete: "ลบ",
      add: "เพิ่ม",
      loading: "กำลังโหลด...",
      noData: "ยังไม่มีข้อมูล",
      details: "รายละเอียด",
      status: "สถานะ",
      active: "ใช้งานอยู่",
      inactive: "ไม่ได้ใช้งาน",
      approved: "อนุมัติแล้ว",
      pending: "รอดำเนินการ",
      completed: "เสร็จสิ้น",
      failed: "ไม่สำเร็จ",
      all: "ทั้งหมด",
      today: "วันนี้",
      date: "วันที่",
      time: "เวลา",
      user: "ผู้ใช้",
      role: "Role",
      email: "อีเมล",
      phone: "เบอร์โทรศัพท์",
      points: "คะแนน",
      locale: "th-TH",
      bannedUntil: "บัญชีถูกระงับการจองถึง",
      requiredFields: "กรุณากรอกข้อมูลให้ครบถ้วน",
      loginBeforeSupport: "กรุณาเข้าสู่ระบบก่อนส่งคำร้อง",
      ticketSent: "ส่ง Ticket ให้ผู้ดูแลระบบเรียบร้อยแล้ว",
      error: "เกิดข้อผิดพลาด",
      contactSupport: "แจ้งปัญหาถึงผู้ดูแลระบบ",
      sending: "กำลังส่ง...",
      sendTicket: "ส่ง Ticket",
      actions: "จัดการ",
      yes: "ใช่",
      no: "ไม่ใช่",
      back: "ย้อนกลับ",
      next: "ถัดไป",
      confirm: "ยืนยัน",
      openMenu: "เปิดเมนูผู้ดูแลระบบ",
      closeMenu: "ปิดเมนู",
      noSignal: "ยังไม่พบสัญญาณ",
      noMac: "ไม่มี MAC",
      source: "ต้นฉบับ",
      maintenance: "บำรุงรักษา",
      revoked: "ยกเลิกสิทธิ์",
      minutes: "นาที",
      day: "วัน",
      allRoles: "ทุก Role",
      adminDashboard: "แดชบอร์ดผู้ดูแลระบบ",
      userId: "User ID",
      brandTagline: "ระบบจองห้อง Lab",
      greeting: "สวัสดี",
      openNavigation: "เปิดเมนูนำทาง",
      openUserMenu: "เปิดเมนูผู้ใช้",
      closeUserMenu: "ปิดเมนูผู้ใช้",
      clickToLogin: "กดเพื่อเข้าสู่ระบบ",
      noEmail: "ไม่ระบุอีเมล",
      noPhone: "ไม่ระบุเบอร์โทรศัพท์",
      unknownName: "ไม่ระบุชื่อ",
      notSpecified: "ไม่ระบุ",
      notSpecifiedRoom: "ไม่ระบุห้อง",
      notSpecifiedDevice: "ไม่ระบุเครื่อง",
      notSpecifiedMac: "ไม่ระบุ MAC",
      notSpecifiedReason: "ไม่ระบุเหตุผล",
      noAdditionalDetails: "ไม่มีรายละเอียดเพิ่มเติม",
      event: "เหตุการณ์",
      until: "ถึง",
      disabled: "ปิดใช้งาน",
      switchToLightTheme: "สลับเป็น Light Theme",
      switchToDarkTheme: "สลับเป็น Dark Theme",
    },
    user: {
      pageTitle: "จองห้อง Lab",
      searchRooms: "ค้นหาด้วยรหัส ชื่อ หรือสถานที่...",
      noLabs: "ยังไม่มีห้อง Lab ที่พร้อมให้บริการ",
      selectRoom: "เลือกห้อง Lab",
      selectDate: "เลือกวันที่",
      dateSelectable: "วันที่เลือกจองได้",
      dateOutsideBookingWindow: "อยู่นอกช่วงที่เปิดให้จอง",
      weekdaysShort: ["จ", "อ", "พ", "พฤ", "ศ", "ส", "อา"],
      selectTime: "เลือกเวลา",
      bookingHistory: "ประวัติการจอง",
      pastReservations: "รายการจองที่ผ่านมา",
      noHistory: "ไม่พบประวัติการจอง",
      reservedTitle: "รายการจองของฉัน",
      noReservations: "ยังไม่มีรายการจอง",
      profileTitle: "โปรไฟล์ของฉัน",
      ticketTitle: "ตั๋วของฉัน",
      noTickets: "ยังไม่มีตั๋ว",
      notifications: "การแจ้งเตือน",
      booking: "จองห้อง",
      bookingSuccess: "จองห้องสำเร็จ",
      confirmBooking: "ยืนยันการจอง",
      cancelBooking: "ยกเลิกการจอง",
      room: "ห้อง",
      lab: "Lab",
      duration: "ระยะเวลา",
      startTime: "เวลาเริ่มต้น",
      endTime: "เวลาสิ้นสุด",
      points: "คะแนน",
      todayPoints: "คะแนนวันนี้",
      permission: "สิทธิ์การจอง",
      searchResults: "ผลการค้นหา",
      selectLabRoom: "เลือกห้อง Lab",
      available: "พร้อมใช้งาน",
      maintenance: "ปิดปรับปรุง",
      users: "ผู้ใช้",
      location: "สถานที่",
      noLabsMatching: "ไม่พบห้อง Lab ที่ตรงกับ",
      adjustSearch: "ลองปรับคำค้นหาใหม่",
      clearSearch: "ล้างการค้นหา",
      backToRooms: "กลับไปยังรายการห้องทั้งหมด",
      capacity: "ความจุ",
      advanceBooking: "จองล่วงหน้าได้ไม่เกิน 2 วัน",
      requiresNotice: "ต้องจองล่วงหน้าอย่างน้อย 2 ชั่วโมง",
      reservedForClass: "สงวนไว้สำหรับชั้นเรียน",
      fullyBooked: "เต็มแล้ว",
      tooClose: "ใกล้เกินไป (ต้องรอ 2 ชั่วโมง)",
      timePassed: "เวลาผ่านไปแล้ว",
      seatsLeft: "ที่นั่งคงเหลือ",
      confirmYourBooking: "ยืนยันการจองของคุณ",
      yourSelection: "รายการที่เลือก",
      loginToBook: "เข้าสู่ระบบเพื่อจอง",
      bookingConfirmed: "ยืนยันการจองสำเร็จ!",
      reservationConfirmed: "การจองห้องของคุณได้รับการยืนยันแล้ว",
      gotIt: "รับทราบ ขอบคุณ",
      reservedStatus: "สถานะการจอง",
      noUpcomingReservations: "ไม่พบรายการจองที่กำลังจะมาถึง",
      cancelReservation: "ยกเลิกการจอง",
      cancelReservationConfirm: "คุณแน่ใจหรือไม่ว่าต้องการยกเลิกการจองนี้ การดำเนินการนี้ไม่สามารถย้อนกลับได้",
      keepReservation: "เก็บรายการจองไว้",
      yesCancel: "ใช่ ยกเลิก",
      pendingCheckIn: "รอยืนยันการเข้าใช้งาน",
      inUse: "กำลังใช้งาน",
      sessionCompleted: "ใช้งานเสร็จแล้ว",
      noShow: "ไม่มาตามการจอง",
      cancelled: "ยกเลิกแล้ว",
      myRequests: "คำร้องของฉัน",
      trackRequests: "ติดตามสถานะคำร้องที่ส่งถึงผู้ดูแลระบบ",
      requests: "คำร้อง",
      requestHistory: "ประวัติคำร้อง",
      requestConversation: "รายการสนทนาและการติดตามปัญหาของคุณ",
      noTicketsSent: "คุณยังไม่เคยส่งคำร้อง",
      supportHelp: "หากพบปัญหา สามารถกดช่วยเหลือจากเมนูด้านซ้ายได้",
      subject: "หัวข้อ",
      message: "รายละเอียด",
      submittedAt: "วันที่ส่ง",
      unknownStatus: "ไม่ทราบสถานะ",
      openTicket: "รอดำเนินการ",
      inProgressTicket: "กำลังดำเนินการ",
      closedTicket: "ดำเนินการเสร็จสิ้น",
      joinedAt: "เข้าร่วมเมื่อ",
      usageStats: "สถิติการใช้งาน",
      bookings: "การจอง",
      personalInfo: "ข้อมูลส่วนตัว",
      studentId: "รหัสนักศึกษา",
      facultyDepartment: "คณะ / สาขา",
      currentPoints: "คะแนนปัจจุบัน",
      myPoints: "คะแนนของฉัน",
      scoreHistory: "ประวัติการเปลี่ยนคะแนน",
      noScoreHistory: "ยังไม่มีประวัติการเปลี่ยนคะแนน",
      statusNormal: "สถานะปกติ",
      lowPointsWarning: "คะแนนต่ำ — โปรดระวังการทำผิดกฎ",
      pointsStatusUnavailable: "ยังตรวจสอบสถานะไม่ได้",
      pointRequestPending: "ส่งคำขอเพิ่มคะแนนแล้ว — รอ Admin พิจารณา",
      zeroPointsMessage: "คะแนนของคุณเหลือ 0 คะแนน กรุณาติดต่อ Admin เพื่อขอความช่วยเหลือ",
      contactAdmin: "ติดต่อ Admin เพื่อขอเพิ่ม",
      pointRequestSentPrefix: "ส่งคำขอเพิ่ม",
      sendingRequest: "กำลังส่งคำขอ...",
      requestSubmitted: "คะแนนแล้ว กรุณารอ Admin พิจารณา",
      bookingSuspendedUntil: "ถูกระงับการจองถึง",
      bookingBlockedByPolicy: "บัญชีนี้ยังไม่สามารถจองห้องได้ตามเกณฑ์คะแนน กรุณาติดต่อผู้ดูแลระบบ",
      bookingDate: "วันที่",
      bookingTime: "เวลา",
      dailyBonusReason: "โบนัสประจำวัน",
      noShowReason: "ไม่มาตามการจอง",
      forbiddenProgramReason: "ใช้โปรแกรมต้องห้าม",
      lateCancelReason: "ยกเลิกการจองกระชั้นชิด",
      sessionCompletedReason: "จบการใช้งานปกติ",
      adminPointAdjustmentReason: "ผู้ดูแลระบบปรับคะแนน",
      studentRole: "นักศึกษา",
      adminRole: "ผู้ดูแลระบบ",
      guestRole: "บุคคลทั่วไป",
      profileLoadFailed: "ไม่สามารถโหลดข้อมูลโปรไฟล์ได้",
      myTicketsLoadFailed: "ไม่สามารถโหลดคำร้องของคุณได้",
      pointsLoadFailed: "ไม่สามารถโหลดข้อมูลคะแนนได้ กรุณาลองใหม่อีกครั้ง",
      pointRequestFailed: "ไม่สามารถส่งคำขอเพิ่มคะแนนได้ กรุณาลองใหม่อีกครั้ง",
      unableToCheckPoints: "ไม่สามารถตรวจสอบคะแนนได้ จึงยังไม่อนุญาตให้จอง",
      unableToFetchLabs: "ไม่สามารถโหลดข้อมูลห้อง Lab ได้ กรุณาตรวจสอบการเชื่อมต่อแล้วลองใหม่",
      unableToFetchSchedule: "ไม่สามารถโหลดตารางห้องได้ กรุณารีเฟรชหน้า",
      bookingFailed: "จองห้องไม่สำเร็จ",
      generalUsagePurpose: "ใช้งานทั่วไป",
    },
    admin: {
      navOverview: "ภาพรวม",
      navLabsAndDevices: "ห้องและอุปกรณ์",
      navUsers: "ผู้ใช้งาน",
      navPointsAndRules: "คะแนนและกฎ",
      navSupport: "การช่วยเหลือ",
      dashboard: "แดชบอร์ด",
      manageLabs: "จัดการ Lab",
      labDevices: "เครื่องประจำ Lab",
      verifyUsers: "ตรวจสอบผู้ใช้",
      userPoints: "คะแนนผู้ใช้",
      pointCriteria: "เกณฑ์คะแนน",
      roleManagement: "จัดการ Role",
      blacklist: "Blacklist",
      ticket: "Ticket",
      dashboardTitle: "แดชบอร์ดผู้ดูแลระบบ",
      manageLabsTitle: "จัดการห้อง Lab",
      devicesTitle: "เครื่องประจำ Lab",
      verifyTitle: "ตรวจสอบผู้ใช้ Guest",
      pointsTitle: "คะแนนของผู้ใช้ทั้งหมด",
      policyTitle: "ปรับเกณฑ์คะแนน",
      rolesTitle: "จัดการบทบาทผู้ใช้งาน",
      blacklistTitle: "จัดการรายการโปรแกรมต้องห้าม",
      ticketTitle: "จัดการ Ticket",
      totalRequests: "คำขอทั้งหมด",
      activeUsers: "ผู้ใช้งานอยู่",
      pendingUsersCard: "ผู้ใช้ที่รอตรวจสอบ",
      supportTickets: "Support Tickets",
      recentReservations: "รายการจองล่าสุด",
      noRecentReservations: "ไม่พบรายการจองล่าสุด",
      searchLabs: "ค้นหา Lab...",
      searchUsers: "ค้นหาชื่อ อีเมล หรือ User ID...",
      searchPendingUsers: "ค้นหาผู้ใช้ที่รอตรวจสอบ...",
      addLab: "เพิ่ม Lab ใหม่",
      pendingUsers: "รอตรวจสอบ",
      allUsers: "ผู้ใช้ทั้งหมด",
      averagePoints: "คะแนนเฉลี่ย",
      belowThreshold: "ต่ำกว่าเกณฑ์",
      bannedUsers: "ถูกระงับการจอง",
      pointRequests: "คำขอเพิ่มแต้ม",
      noPendingUsers: "ไม่มีผู้ใช้ที่รอการตรวจสอบ",
      noRoles: "ยังไม่มีข้อมูล Role",
      noBlacklist: "ยังไม่มีโปรแกรมต้องห้าม",
      noDevices: "ยังไม่มีเครื่องที่ลงทะเบียน",
      deviceHeading: "เครื่องประจำ Lab",
      deviceSubtitle: "ลงทะเบียนและควบคุมว่าเครื่องใดอยู่ใน Lab ใด",
      machine: "เครื่อง",
      agent: "Agent",
      lastSignal: "สัญญาณล่าสุด",
      manage: "การจัดการ",
      saveDevice: "บันทึก",
      savingDevice: "กำลังบันทึก",
      deviceRegistered: "บันทึกการตั้งค่าเครื่องแล้ว",
      deviceSaveFailed: "บันทึกข้อมูลไม่สำเร็จ",
      labsHeading: "จัดการห้อง Lab",
      labsSubtitle: "สร้าง แก้ไข และกำหนดตารางการใช้งานห้อง Lab",
      rolesHeading: "จัดการบทบาทผู้ใช้งาน",
      rolesSubtitle: "กำหนดสิทธิ์และบทบาทให้กับผู้ใช้งานในระบบ",
      rolesInSystem: "Roles ในระบบ",
      assignRole: "กำหนด Role ให้ User",
      roleDisplayName: "ชื่อแสดงผล",
      roleUsers: "ผู้ใช้งาน",
      roleType: "ประเภท",
      editRoleTitle: "แก้ไขชื่อแสดงผล Role",
      roleKey: "Role key",
      cannotChangeSelf: "ไม่สามารถเปลี่ยน Role ตัวเอง",
      noMatchingUsers: "ไม่พบ User ตามเงื่อนไขที่เลือก",
      verifyHeading: "ตรวจสอบผู้ใช้ Guest",
      verifySubtitle: "ตรวจสอบและอนุมัติผู้ใช้ภายนอกก่อนให้สามารถจองห้อง Lab ได้",
      noPendingVerifications: "ไม่มีผู้ใช้ที่รอตรวจสอบ",
      allGuestsUpToDate: "บัญชี Guest ทั้งหมดได้รับการตรวจสอบแล้ว",
      noMatchingGuestUsers: "ไม่พบผู้ใช้ที่ตรงกัน",
      adjustGuestSearch: "ลองค้นหาด้วยชื่อ อีเมล หรือเบอร์โทรศัพท์อื่น",
      guestUser: "ผู้ใช้ Guest",
      pending: "รอดำเนินการ",
      reject: "ปฏิเสธ",
      approve: "อนุมัติ",
      saving: "กำลังบันทึก...",
      userPointsHeading: "คะแนนของผู้ใช้ทั้งหมด",
      pointSummaryDate: "คะแนนรายวัน ณ",
      pointFilter: "ตัวกรอง",
      pointSort: "เรียงตาม",
      allUsersFilter: "ผู้ใช้ทั้งหมด",
      lowPoints: "คะแนนต่ำ",
      bookingBanned: "ถูกระงับการจอง",
      bookingAllowed: "จองได้",
      pointsAscending: "คะแนนน้อยไปมาก",
      pointsDescending: "คะแนนมากไปน้อย",
      userNameSort: "ชื่อผู้ใช้",
      accumulatedPoints: "คะแนนสะสม",
      dailyPoints: "คะแนนวันนี้",
      bookingRights: "สิทธิ์การจอง",
      lastUpdated: "อัปเดตล่าสุด",
      blockedProgramHeading: "จัดการรายการโปรแกรมต้องห้าม",
      blockedProgramSubtitle: "โปรแกรมที่ Agent จะตรวจพบและแจ้งเตือนตามนโยบายของ Lab",
      programsBlocked: "โปรแกรมถูกระงับ",
      unknownProgram: "ไม่ระบุชื่อโปรแกรม",
      addBlockedProgram: "เพิ่มโปรแกรมต้องห้าม",
      programName: "ชื่อโปรแกรม",
      description: "รายละเอียด",
      editProgram: "แก้ไขโปรแกรม",
      addProgram: "เพิ่มโปรแกรม",
      noBlockedPrograms: "ยังไม่มีโปรแกรมต้องห้าม",
      pointPolicyHeading: "ปรับเกณฑ์คะแนน",
      pointPolicySubtitle: "ตั้งค่าคะแนนที่ใช้กับการตรวจจับ การจบ Session การแจ้งเตือน และสิทธิ์การจองของผู้ใช้",
      pointPolicyInfo: "ค่าใหม่จะมีผลกับเหตุการณ์คะแนนและการตรวจสอบสิทธิ์การจองในครั้งถัดไป ประวัติคะแนนเดิมจะไม่ถูกแก้ไข",
      refreshData: "รีเฟรชข้อมูล",
      restoreDefaults: "คืนค่าเริ่มต้นในฟอร์ม",
      savePolicy: "บันทึกเกณฑ์คะแนน",
      bookingBanCriteria: "เกณฑ์การระงับการจอง",
      policyScope: "ขอบเขตของการตั้งค่า",
      ticketId: "ID",
      ticketUserId: "User ID",
      ticketSubject: "หัวข้อ",
      ticketMessage: "รายละเอียด",
      ticketSubmitted: "วันที่ส่ง",
      ticketStatus: "สถานะ",
      ticketManage: "จัดการ",
      currentRole: "Role ปัจจุบัน",
      createdAt: "วันที่สร้าง",
      changeRole: "เปลี่ยน Role",
      systemRole: "System role",
      customRole: "Custom role",
      selectRole: "เลือก Role",
      roleChangeDescription: "การเปลี่ยน Role จะมีผลกับการเข้าใช้งานครั้งถัดไป ผู้ดูแลระบบจะไม่สามารถเปลี่ยน Role ของตัวเองได้",
      unableToLoadRoles: "ไม่สามารถโหลดข้อมูล Role ได้",
      unableToChangeRole: "ไม่สามารถเปลี่ยน Role ของผู้ใช้ได้",
      unableToSaveRoleName: "ไม่สามารถบันทึกชื่อ Role ได้",
      pointsTableEmpty: "ไม่พบข้อมูลผู้ใช้ตามเงื่อนไขที่เลือก",
      addPointsRequest: "ขอเพิ่ม",
      pointsTotal: "คะแนน",
      requestedAt: "ส่งคำขอเมื่อ",
      warningWhenAtMost: "เตือนเมื่อ ≤",
      reducePointsTest: "ลด 10 แต้ม (ทดสอบ)",
      reducingPoints: "กำลังลด...",
      resetPointsTest: "Reset เป็น 100 (ทดสอบ)",
      resettingPoints: "กำลัง Reset...",
      viewDetails: "ดูข้อมูล",
      usersCountSummary: "แสดง {start}–{end} จาก {total} ผู้ใช้",
      maxPointsHint: "คะแนนสูงสุด 100 คะแนน",
      pendingTicketStatus: "รอดำเนินการ",
      closedTicketStatus: "ปิดแล้ว",
      closeTicket: "ปิด Ticket",
      resolved: "ดำเนินการแล้ว",
      noTickets: "ยังไม่มี Ticket",
      noPhoneProvided: "ไม่ระบุเบอร์โทรศัพท์",
      pointThreshold: "ต่ำกว่า (คะแนน)",
      suspensionDays: "ระงับ (วัน)",
      lab: "Lab",
      blockedProgramPlaceholder: "เช่น โปรแกรมที่ไม่อนุญาตให้ใช้งาน",
      allLaboratoryRooms: "ห้องปฏิบัติการทั้งหมด",
      active: "เปิดใช้งาน",
      disabled: "ปิดใช้งาน",
      users: "ผู้ใช้",
      backToAllRooms: "กลับไปยังรายการห้องทั้งหมด",
      capacity: "ความจุ",
      location: "สถานที่",
      editLabInformation: "แก้ไขข้อมูล Lab",
      labCode: "รหัส Lab",
      labName: "ชื่อ Lab",
      deleteLab: "ลบ Lab",
      saveChanges: "บันทึกการเปลี่ยนแปลง",
      disableLaboratory: "ปิดใช้งานห้องปฏิบัติการนี้",
      enableLaboratory: "เปิดใช้งานห้องปฏิบัติการนี้",
      suspendRoomBookings: "ระงับการจองห้องนี้",
      allowRoomBookings: "อนุญาตให้จองห้องนี้",
      disableAccess: "ปิดสิทธิ์การใช้งาน",
      enableAccess: "เปิดสิทธิ์การใช้งาน",
      classSchedules: "ตารางเรียน",
      classSchedulesHint: "ช่วงเวลาที่เพิ่มจะไม่เปิดให้ผู้ใช้จอง",
      addClass: "เพิ่มตารางเรียน",
      createNewLab: "สร้าง Lab ใหม่",
      createLab: "สร้าง Lab",
      courseCode: "รหัสวิชา",
      courseName: "ชื่อวิชา",
      instructorName: "ชื่อผู้สอน",
      dayOfWeek: "วันในสัปดาห์",
      timeSlot: "ช่วงเวลา",
      semester: "ภาคเรียน",
      academicYear: "ปีการศึกษา",
      validFrom: "วันที่เริ่มมีผล",
      validUntil: "วันที่สิ้นสุด",
      editClassSchedule: "แก้ไขตารางเรียน",
      addClassSchedule: "เพิ่มตารางเรียน",
      cancelAction: "ยกเลิก",
      createFailed: "สร้างไม่สำเร็จ",
      updateFailed: "อัปเดตไม่สำเร็จ",
      updateSucceeded: "อัปเดตสำเร็จ",
      deleteSucceeded: "ลบสำเร็จ",
      deleteFailed: "ลบไม่สำเร็จ",
      missingRequiredFields: "กรุณากรอกข้อมูลที่จำเป็นให้ครบถ้วน",
      invalidScheduleDates: "วันที่สิ้นสุดต้องไม่อยู่ก่อนวันที่เริ่มต้น",
      operationFailed: "ดำเนินการไม่สำเร็จ",
      roleChanged: "เปลี่ยน Role ของผู้ใช้เรียบร้อยแล้ว",
      roleNameSaved: "บันทึกชื่อ Role เรียบร้อยแล้ว",
      roleKeyInfo: "Role key เป็นข้อมูลภายในระบบ จึงคงเดิมเพื่อไม่ให้กระทบการเข้าสู่ระบบและสิทธิ์ผู้ดูแล ส่วนชื่อแสดงผลและการกำหนด Role ให้ผู้ใช้สามารถแก้ไขได้",
      roleDisplayNameInfo: "Role name ใช้เป็น key ภายในระบบ ส่วนชื่อแสดงผลสามารถปรับให้เหมาะกับหน่วยงานได้",
      allRolesSummary: "Roles ทั้งหมด",
      usersWithRole: "ผู้ใช้ที่มี Role",
      systemRolesSummary: "System Roles",
      pointRequestsCount: "รายการ",
      requestPoints: "ขอเพิ่ม",
      requestSentAt: "ส่งคำขอเมื่อ",
      showing: "แสดง",
      of: "จาก",
      banCriteriaDescription: "กำหนดจำนวนวันที่ระงับการจองตามระดับคะแนน หากกำหนด 0 วัน จะไม่สร้างการระงับในระดับนั้น",
      banThresholdOrderWarning: "ค่าเกณฑ์ต้องเรียงจากน้อยไปมาก และเกณฑ์สูงสุดต้องไม่เกินคะแนนขั้นต่ำสำหรับการจอง",
      testActionsFixedPolicy: "ปุ่มลดคะแนนและ Reset สำหรับการทดสอบใช้ค่า -10 และ 100 คงที่ เพื่อไม่ให้เปลี่ยนตามเกณฑ์จริง",
      pointEarnedTitle: "คะแนนที่ได้รับ",
      pointEarnedDescription: "กำหนดคะแนนที่จะเพิ่มให้ผู้ใช้จากกิจกรรมปกติ",
      dailyBonusPolicy: "โบนัสประจำวัน",
      dailyBonusPolicyHint: "คะแนนที่ได้รับเมื่อระบบเริ่มวันใหม่ (0–10)",
      completeSessionPolicy: "จบ Session ปกติ",
      completeSessionPolicyHint: "คะแนนเมื่อออกจาก Session ตามปกติ (0–20)",
      pointDeductedTitle: "คะแนนที่ถูกหัก",
      pointDeductedDescription: "ค่าเหล่านี้ต้องเป็นศูนย์หรือติดลบ เพื่อป้องกันการเพิ่มคะแนนจากเหตุการณ์ผิดกฎ",
      noShowPolicy: "ไม่มาตามการจอง (No-show)",
      noShowPolicyHint: "หักคะแนนเมื่อหมดเวลาจองแล้วไม่เข้าใช้งาน (-100 ถึง 0)",
      forbiddenProgramPolicy: "ใช้โปรแกรมต้องห้าม",
      forbiddenProgramPolicyHint: "หักคะแนนเมื่อ Agent ตรวจพบโปรแกรมที่ผิดกฎ (-100 ถึง 0)",
      lateCancelPolicy: "ยกเลิกการจองกระชั้นชิด",
      lateCancelPolicyHint: "หักคะแนนเมื่อยกเลิกการจองใกล้เวลาใช้งาน (-100 ถึง 0)",
      recoveryAndBookingTitle: "การกู้คะแนนและสิทธิ์การจอง",
      recoveryAndBookingDescription: "กำหนดจำนวนคะแนนที่ขอคืนได้ รวมถึงเกณฑ์แจ้งเตือนและเกณฑ์อนุญาตให้จอง",
      pointsReturnedOnApproval: "คะแนนที่คืนเมื่ออนุมัติคำขอ",
      pointsReturnedHint: "จำนวนคะแนนที่ผู้ใช้ขอคืนได้เมื่อคะแนนเป็น 0 (1–100)",
      warningThresholdLabel: "เกณฑ์แจ้งเตือน",
      warningThresholdHint: "แจ้งเตือนเมื่อคะแนนไม่เกินค่านี้ (0–100)",
      banLevelOne: "ระดับ 1 · ต่ำกว่าเกณฑ์วิกฤต",
      banLevelTwo: "ระดับ 2 · คะแนนต่ำ",
      banLevelThree: "ระดับ 3 · คะแนนเริ่มเตือน",
      banLevelFour: "ระดับ 4 · ต่ำกว่าเกณฑ์จอง",
      deleteTicketFailed: "เกิดข้อผิดพลาดในการอัปเดตสถานะ",
      ticketStatusUpdateFailed: "เกิดข้อผิดพลาดในการอัปเดตสถานะ",
      verifyUsersPending: "รอการตรวจสอบ {count} คน",
      pointsPageDescription: "ตรวจสอบคะแนนสะสม คะแนนวันนี้ และสิทธิ์การจองของทุกบัญชี",
      bookingDependsOnBan: "การจองขึ้นกับสถานะการระงับเท่านั้น",
      course: "รายวิชา",
      instructor: "ผู้สอน",
      term: "ภาคเรียน",
      action: "การจัดการ",
      weekdayMonday: "วันจันทร์",
      weekdayTuesday: "วันอังคาร",
      weekdayWednesday: "วันพุธ",
      weekdayThursday: "วันพฤหัสบดี",
      weekdayFriday: "วันศุกร์",
      weekdaySaturday: "วันเสาร์",
      weekdaySunday: "วันอาทิตย์",
      confirmDeleteLabPrefix: "ยืนยันการลบ Lab",
      confirmDeleteLabSuffix: "ตารางเรียนทั้งหมดจะถูกลบตามไปด้วย การดำเนินการนี้ไม่สามารถย้อนกลับได้",
      deleteScheduleConfirmation: "ยืนยันการลบตารางเรียนนี้หรือไม่",
      labCreated: "สร้าง Lab เรียบร้อยแล้ว",
      scheduleSaved: "บันทึกตารางเรียนเรียบร้อยแล้ว",
      pendingUsersLoadFailed: "ไม่สามารถโหลดรายการผู้ใช้ที่รอตรวจสอบได้",
      verifyUserFailed: "ไม่สามารถดำเนินการกับผู้ใช้ได้",
      rejectUserConfirmation: "ยืนยันการปฏิเสธและลบบัญชีผู้ใช้นี้หรือไม่",
      accountsInSystem: "บัญชีในระบบ",
      activeBans: "มี Ban ที่ยังใช้งาน",
      noRoleAssigned: "ยังไม่มี Role",
      appNameRequired: "กรุณากรอกชื่อโปรแกรม",
      blacklistOperationFailed: "ดำเนินการกับรายการ Blacklist ไม่สำเร็จ",
      confirmRemoveBlacklistItem: "ยืนยันการนำออกจาก Blacklist",
      deleteBlacklistFailed: "ลบรายการ Blacklist ไม่สำเร็จ",
      policyAdminLoginRequired: "กรุณาเข้าสู่ระบบด้วยบัญชี Admin ก่อนปรับเกณฑ์คะแนน",
      policySaveAdminLoginRequired: "กรุณาเข้าสู่ระบบด้วยบัญชี Admin ก่อนบันทึกเกณฑ์คะแนน",
      loadPolicyFailed: "ไม่สามารถโหลดเกณฑ์คะแนนได้",
      savePolicyFailed: "ไม่สามารถบันทึกเกณฑ์คะแนนได้",
      policySaved: "บันทึกเกณฑ์คะแนนเรียบร้อยแล้ว มีผลกับเหตุการณ์ใหม่หลังจากนี้",
      policyDefaultsRestored: "คืนค่าเริ่มต้นในฟอร์มแล้ว กดบันทึกเกณฑ์คะแนนเพื่อใช้งานจริง",
      policyIntegerRequired: "กรุณากรอกค่าเป็นจำนวนเต็มให้ครบทุกช่อง",
      policyRangeInvalid: "มีค่าบางรายการอยู่นอกช่วงที่กำหนด",
      policyThresholdOrderInvalid: "เกณฑ์คะแนนสำหรับ Ban ต้องเรียงจากน้อยไปมากและไม่ซ้ำกัน",
      adminLoginRequired: "กรุณาเข้าสู่ระบบด้วยบัญชี Admin ก่อนดูคะแนนผู้ใช้",
      userDetailLoginRequired: "กรุณาเข้าสู่ระบบด้วยบัญชี Admin ก่อนดูข้อมูลผู้ใช้",
      pointRequestLoginRequired: "กรุณาเข้าสู่ระบบด้วยบัญชี Admin ก่อนจัดการคำขอเพิ่มคะแนน",
      testDeductionLoginRequired: "กรุณาเข้าสู่ระบบด้วยบัญชี Admin ก่อนทดสอบการลดคะแนน",
      testResetLoginRequired: "กรุณาเข้าสู่ระบบด้วยบัญชี Admin ก่อน Reset คะแนนทดสอบ",
      loadUserPointsFailed: "ไม่สามารถโหลดคะแนนของผู้ใช้ได้",
      loadUserDetailFailed: "ไม่สามารถโหลดข้อมูลและประวัติของผู้ใช้ได้",
      pointRequestActionFailed: "ไม่สามารถจัดการคำขอเพิ่มคะแนนได้",
      testDeductionFailed: "ไม่สามารถทดสอบการลดคะแนนได้",
      testResetFailed: "ไม่สามารถ Reset คะแนนทดสอบได้",
      testDeductionConfirmPrefix: "ต้องการลดคะแนนของ",
      testDeductionConfirmSuffix: "จำนวน 10 คะแนนเพื่อทดสอบหรือไม่?",
      testResetConfirmPrefix: "ต้องการคืนคะแนนของ",
      testResetConfirmSuffix: "กลับเป็น 100 เพื่อเริ่มการทดสอบใหม่หรือไม่?",
      userDetails: {
        bookings: "การจอง",
        sessions: "Session",
        programs: "โปรแกรม",
        pointHistory: "ประวัติคะแนน",
        violations: "การละเมิด",
        noBookingHistory: "ยังไม่มีประวัติการจอง",
        noBookingHistoryDescription: "ผู้ใช้นี้ยังไม่เคยสร้างรายการจองห้อง",
        bookingDateTime: "วันและเวลา",
        room: "ห้อง",
        purpose: "วัตถุประสงค์",
        status: "สถานะ",
        noSessions: "ยังไม่มีประวัติ Session",
        noSessionsDescription: "ยังไม่มีข้อมูลการเข้าใช้งานห้องของผู้ใช้นี้",
        checkInOut: "เข้า - ออก",
        deviceInUse: "เครื่องที่ใช้งาน",
        endReason: "สาเหตุจบ",
        noProgramUsage: "ยังไม่มีประวัติการใช้โปรแกรม",
        noProgramUsageDescription: "Agent ยังไม่มีข้อมูลโปรแกรมจาก Session ของผู้ใช้นี้",
        time: "เวลา",
        program: "โปรแกรม",
        duration: "ระยะเวลา",
        device: "เครื่อง",
        noViolations: "ไม่พบการละเมิด",
        noViolationsDescription: "ยังไม่มีรายการใช้โปรแกรมที่ผิดกฎของผู้ใช้นี้",
        detectedAt: "ตรวจพบเมื่อ",
        evidence: "หลักฐาน",
        actionTaken: "การดำเนินการ",
        noPointsHistory: "ยังไม่มีประวัติการปรับคะแนน",
        noPointsHistoryDescription: "คะแนนของผู้ใช้นี้ยังไม่เคยมีรายการเปลี่ยนแปลง",
        dateTime: "วันเวลา",
        reason: "เหตุผล",
        pointChange: "การเปลี่ยนแปลง",
        pointsAfter: "คะแนนหลังรายการ",
        dailyPoints: "คะแนนรายวัน",
        dailyPointsLimit: "แสดงย้อนหลังไม่เกิน 100 รายการ",
        noDailyPoints: "ยังไม่มีคะแนนรายวัน",
        accountDetails: "ข้อมูลบัญชี",
        accountStatusAndUsage: "สถานะคะแนนและการใช้งาน",
        studentId: "รหัสนักศึกษา",
        faculty: "คณะ",
        department: "สาขา",
        createdAt: "สร้างบัญชีเมื่อ",
        bookingAccess: "สิทธิ์การจอง",
        historySummary: "ข้อมูลประวัติ",
        accountUsable: "บัญชีใช้งานได้",
        awaitingReview: "รอตรวจสอบ",
        noRoom: "ไม่ระบุห้อง",
        noDevice: "ไม่ระบุเครื่อง",
        noMac: "ไม่ระบุ MAC",
        noReason: "ไม่ระบุเหตุผล",
        noProgram: "ไม่ระบุ",
        noProcess: "ไม่ระบุ process",
        noDetails: "ไม่มีรายละเอียดเพิ่มเติม",
        event: "เหตุการณ์",
        recordedEvent: "บันทึกเหตุการณ์",
        noData: "ไม่มีข้อมูล",
        until: "ถึง",
        seconds: "วินาที",
        minutes: "นาที",
        bookingReserved: "รอยืนยัน",
        bookingAttended: "เข้าใช้งานแล้ว",
        bookingCompleted: "เสร็จสิ้น",
        bookingCancelled: "ยกเลิก",
        bookingNoShow: "ไม่มาตามนัด",
        sessionActive: "กำลังใช้งาน",
        sessionCompleted: "จบปกติ",
        sessionAbandoned: "ขาดการเชื่อมต่อ",
        roleStudent: "Student",
        roleGuest: "Guest",
        roleUser: "User",
        roleAdministrator: "Administrator",
        roleSystemAdmin: "System Admin",
        pointDailyBonus: "โบนัสประจำวัน",
        pointNoShow: "ไม่มาตามการจอง",
        pointForbiddenProgram: "ใช้โปรแกรมต้องห้าม",
        pointLateCancel: "ยกเลิกการจองกระชั้นชิด",
        pointSessionComplete: "จบ Session ปกติ",
        pointAdminGrant: "ผู้ดูแลระบบปรับคะแนน",
        pointAdjustment: "ปรับคะแนน",
      },
    },
  },
  en: {
    language: {
      switchTo: "ภาษาไทย",
      current: "English",
      aria: "Change language to Thai",
    },
    common: {
      labReserve: "Lab Reserve",
      reserved: "Reserved",
      history: "History",
      myTickets: "My Tickets",
      support: "Support",
      notifications: "Notifications",
      noNotifications: "No notifications yet",
      systemAdmin: "System Admin",
      administrator: "Administrator",
      profile: "Profile",
      manageAccount: "Manage your account",
      guestUser: "Guest User",
      login: "Log in",
      settings: "Settings",
      logout: "Log out",
      search: "Search...",
      refresh: "Refresh",
      save: "Save",
      cancel: "Cancel",
      close: "Close",
      edit: "Edit",
      delete: "Delete",
      add: "Add",
      loading: "Loading...",
      noData: "No data available",
      details: "Details",
      status: "Status",
      active: "Active",
      inactive: "Inactive",
      approved: "Approved",
      pending: "Pending",
      completed: "Completed",
      failed: "Failed",
      all: "All",
      today: "Today",
      date: "Date",
      time: "Time",
      user: "User",
      role: "Role",
      email: "Email",
      phone: "Phone",
      points: "points",
      locale: "en-GB",
      bannedUntil: "Booking is suspended until",
      requiredFields: "Please complete all fields",
      loginBeforeSupport: "Please log in before sending a request",
      ticketSent: "Ticket sent to the administrator",
      error: "Error",
      contactSupport: "Contact the administrator",
      sending: "Sending...",
      sendTicket: "Send ticket",
      actions: "Actions",
      yes: "Yes",
      no: "No",
      back: "Back",
      next: "Next",
      confirm: "Confirm",
      openMenu: "Open admin menu",
      closeMenu: "Close menu",
      noSignal: "No signal yet",
      noMac: "No MAC",
      source: "Source",
      maintenance: "Maintenance",
      revoked: "Revoked",
      minutes: "minutes",
      day: "days",
      allRoles: "All roles",
      adminDashboard: "Admin dashboard",
      userId: "User ID",
      brandTagline: "Reserve a lab",
      greeting: "Hi",
      openNavigation: "Open navigation menu",
      openUserMenu: "Open user menu",
      closeUserMenu: "Close user menu",
      clickToLogin: "Click to log in",
      noEmail: "No email provided",
      noPhone: "No phone number provided",
      unknownName: "Unknown name",
      notSpecified: "Not specified",
      notSpecifiedRoom: "Room not specified",
      notSpecifiedDevice: "Device not specified",
      notSpecifiedMac: "MAC not specified",
      notSpecifiedReason: "Reason not specified",
      noAdditionalDetails: "No additional details",
      event: "Event",
      until: "until",
      disabled: "Disabled",
      switchToLightTheme: "Switch to light theme",
      switchToDarkTheme: "Switch to dark theme",
    },
    user: {
      pageTitle: "Lab Reserve",
      searchRooms: "Search by code, name, or location...",
      noLabs: "No labs are currently available",
      selectRoom: "Select a lab",
      selectDate: "Select a date",
      dateSelectable: "Available to select",
      dateOutsideBookingWindow: "Outside the booking window",
      weekdaysShort: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
      selectTime: "Select a time",
      bookingHistory: "Booking History",
      pastReservations: "Past Reservations",
      noHistory: "No booking history found",
      reservedTitle: "My Reservations",
      noReservations: "No reservations yet",
      profileTitle: "My Profile",
      ticketTitle: "My Tickets",
      noTickets: "No tickets yet",
      notifications: "Notifications",
      booking: "Book a lab",
      bookingSuccess: "Booking created successfully",
      confirmBooking: "Confirm booking",
      cancelBooking: "Cancel booking",
      room: "Room",
      lab: "Lab",
      duration: "Duration",
      startTime: "Start time",
      endTime: "End time",
      points: "Points",
      todayPoints: "Today's points",
      permission: "Booking access",
      searchResults: "Search results",
      selectLabRoom: "Select a lab room",
      available: "Available",
      maintenance: "Maintenance",
      users: "Users",
      location: "Location",
      noLabsMatching: "No labs found matching",
      adjustSearch: "Try adjusting your search keywords.",
      clearSearch: "Clear search",
      backToRooms: "Back to all rooms",
      capacity: "Capacity",
      advanceBooking: "Advance booking up to 2 days",
      requiresNotice: "Requires 2 hours advance notice",
      reservedForClass: "Reserved for class",
      fullyBooked: "Fully booked",
      tooClose: "Too close (wait 2 hours)",
      timePassed: "Time passed",
      seatsLeft: "Seats left",
      confirmYourBooking: "Confirm your booking",
      yourSelection: "Your selection",
      loginToBook: "Log in to book",
      bookingConfirmed: "Booking confirmed!",
      reservationConfirmed: "Your lab reservation has been confirmed.",
      gotIt: "Got it, thanks",
      reservedStatus: "Reservation status",
      noUpcomingReservations: "No upcoming reservations found",
      cancelReservation: "Cancel Reservation",
      cancelReservationConfirm: "Are you sure you want to cancel this booking? This action cannot be undone.",
      keepReservation: "Keep it",
      yesCancel: "Yes, cancel",
      pendingCheckIn: "Awaiting check-in",
      inUse: "In use",
      sessionCompleted: "Completed",
      noShow: "No-show",
      cancelled: "Cancelled",
      myRequests: "My requests",
      trackRequests: "Track requests sent to the administrator",
      requests: "requests",
      requestHistory: "Request history",
      requestConversation: "Conversations and updates for your requests",
      noTicketsSent: "You have not sent any requests",
      supportHelp: "If you need help, use Support in the left menu",
      subject: "Subject",
      message: "Message",
      submittedAt: "Submitted",
      unknownStatus: "Unknown status",
      openTicket: "Open",
      inProgressTicket: "In progress",
      closedTicket: "Resolved",
      joinedAt: "Joined",
      usageStats: "Usage statistics",
      bookings: "Bookings",
      personalInfo: "Personal information",
      studentId: "Student ID",
      facultyDepartment: "Faculty / Department",
      currentPoints: "Current points",
      myPoints: "My points",
      scoreHistory: "Point history",
      noScoreHistory: "No point history yet",
      statusNormal: "Status: normal",
      lowPointsWarning: "Low points — please follow the lab rules",
      pointsStatusUnavailable: "Point status unavailable",
      pointRequestPending: "Point request sent — waiting for admin review",
      zeroPointsMessage: "You have 0 points. Contact an admin for assistance.",
      contactAdmin: "Contact admin to request",
      pointRequestSentPrefix: "You requested",
      sendingRequest: "Sending request...",
      requestSubmitted: "points. Please wait for admin review",
      bookingSuspendedUntil: "Booking suspended until",
      bookingBlockedByPolicy: "This account cannot book a room under the points policy. Please contact an administrator.",
      bookingDate: "Date",
      bookingTime: "Time",
      dailyBonusReason: "Daily bonus",
      noShowReason: "No-show",
      forbiddenProgramReason: "Forbidden program use",
      lateCancelReason: "Late cancellation",
      sessionCompletedReason: "Session completed normally",
      adminPointAdjustmentReason: "Administrator point adjustment",
      studentRole: "Student",
      adminRole: "Administrator",
      guestRole: "Guest",
      profileLoadFailed: "Unable to load profile information",
      myTicketsLoadFailed: "Unable to load your requests",
      pointsLoadFailed: "Unable to load point information. Please try again.",
      pointRequestFailed: "Unable to submit the point request. Please try again.",
      unableToCheckPoints: "Unable to check points, so booking is unavailable",
      unableToFetchLabs: "Unable to load labs. Check your connection and try again.",
      unableToFetchSchedule: "Unable to load the room schedule. Please refresh the page.",
      bookingFailed: "Booking failed",
      generalUsagePurpose: "General use",
    },
    admin: {
      navOverview: "Overview",
      navLabsAndDevices: "Labs & devices",
      navUsers: "Users",
      navPointsAndRules: "Points & rules",
      navSupport: "Support",
      dashboard: "Dashboard",
      manageLabs: "Manage Labs",
      labDevices: "Lab Devices",
      verifyUsers: "Verify Users",
      userPoints: "User Points",
      pointCriteria: "Point Criteria",
      roleManagement: "Role Management",
      blacklist: "Blacklist",
      ticket: "Ticket",
      dashboardTitle: "Admin Dashboard",
      manageLabsTitle: "Manage Laboratory Rooms",
      devicesTitle: "Lab Devices",
      verifyTitle: "Verify Guest Users",
      pointsTitle: "All User Points",
      policyTitle: "Point Criteria",
      rolesTitle: "Role Management",
      blacklistTitle: "Blocked Programs",
      ticketTitle: "Ticket Manager",
      totalRequests: "Total requests",
      activeUsers: "Active users",
      pendingUsersCard: "Pending users",
      supportTickets: "Support tickets",
      recentReservations: "Recent reservations",
      noRecentReservations: "No recent reservations found",
      searchLabs: "Search labs...",
      searchUsers: "Search name, email, or User ID...",
      searchPendingUsers: "Search pending users...",
      addLab: "Add New Lab",
      pendingUsers: "Pending review",
      allUsers: "All users",
      averagePoints: "Average points",
      belowThreshold: "Below threshold",
      bannedUsers: "Booking bans",
      pointRequests: "Point requests",
      noPendingUsers: "No users are waiting for review",
      noRoles: "No roles found",
      noBlacklist: "No blocked programs",
      noDevices: "No registered devices",
      deviceHeading: "Lab Devices",
      deviceSubtitle: "Register devices and control which lab they belong to",
      machine: "Device",
      agent: "Agent",
      lastSignal: "Last signal",
      manage: "Actions",
      saveDevice: "Save",
      savingDevice: "Saving...",
      deviceRegistered: "Device settings saved",
      deviceSaveFailed: "Could not save the device",
      labsHeading: "Manage Laboratory Rooms",
      labsSubtitle: "Create, edit, and configure lab room schedules",
      rolesHeading: "Role Management",
      rolesSubtitle: "Manage access roles and permissions for system users",
      rolesInSystem: "Roles in the system",
      assignRole: "Assign role to users",
      roleDisplayName: "Display name",
      roleUsers: "Users",
      roleType: "Type",
      editRoleTitle: "Edit role display name",
      roleKey: "Role key",
      cannotChangeSelf: "You cannot change your own role",
      noMatchingUsers: "No users match the selected filters",
      verifyHeading: "Verify Guest Users",
      verifySubtitle: "Review and approve external users before they can book labs.",
      noPendingVerifications: "No pending verifications",
      allGuestsUpToDate: "All guest accounts are up to date.",
      noMatchingGuestUsers: "No matching users",
      adjustGuestSearch: "Try another name, email, or phone number",
      guestUser: "Guest User",
      pending: "Pending",
      reject: "Reject",
      approve: "Approve",
      saving: "Saving...",
      userPointsHeading: "All User Points",
      pointSummaryDate: "Daily points as of",
      pointFilter: "Filter",
      pointSort: "Sort by",
      allUsersFilter: "All users",
      lowPoints: "Low points",
      bookingBanned: "Booking banned",
      bookingAllowed: "Booking allowed",
      pointsAscending: "Points: low to high",
      pointsDescending: "Points: high to low",
      userNameSort: "User name",
      accumulatedPoints: "Accumulated points",
      dailyPoints: "Today's points",
      bookingRights: "Booking access",
      lastUpdated: "Last updated",
      blockedProgramHeading: "Blocked Programs",
      blockedProgramSubtitle: "Programs that the Agent detects and handles according to lab policy",
      programsBlocked: "programs blocked",
      unknownProgram: "Unnamed program",
      addBlockedProgram: "Add blocked program",
      programName: "Program name",
      description: "Description",
      editProgram: "Edit program",
      addProgram: "Add program",
      noBlockedPrograms: "No blocked programs",
      pointPolicyHeading: "Point Criteria",
      pointPolicySubtitle: "Configure points used for detection, session completion, alerts, and booking access",
      pointPolicyInfo: "New values apply to future point events and booking access checks. Existing point history is not changed.",
      refreshData: "Refresh data",
      restoreDefaults: "Restore form defaults",
      savePolicy: "Save point criteria",
      bookingBanCriteria: "Booking suspension criteria",
      policyScope: "Configuration scope",
      ticketId: "ID",
      ticketUserId: "User ID",
      ticketSubject: "Subject",
      ticketMessage: "Message",
      ticketSubmitted: "Submitted",
      ticketStatus: "Status",
      ticketManage: "Actions",
      currentRole: "Current role",
      createdAt: "Created at",
      changeRole: "Change role",
      systemRole: "System role",
      customRole: "Custom role",
      selectRole: "Select a role",
      roleChangeDescription: "Role changes take effect on the user's next sign-in. Administrators cannot change their own role.",
      unableToLoadRoles: "Unable to load role data",
      unableToChangeRole: "Unable to change the user's role",
      unableToSaveRoleName: "Unable to save the role name",
      pointsTableEmpty: "No users match the selected filters",
      addPointsRequest: "Request points",
      pointsTotal: "points",
      requestedAt: "Requested at",
      warningWhenAtMost: "Warn at ≤",
      reducePointsTest: "Deduct 10 points (test)",
      reducingPoints: "Deducting...",
      resetPointsTest: "Reset to 100 (test)",
      resettingPoints: "Resetting...",
      viewDetails: "View details",
      usersCountSummary: "Showing {start}–{end} of {total} users",
      maxPointsHint: "Maximum score: 100 points",
      pendingTicketStatus: "Open",
      closedTicketStatus: "Closed",
      closeTicket: "Close ticket",
      resolved: "Resolved",
      noTickets: "No tickets yet",
      noPhoneProvided: "No phone number provided",
      pointThreshold: "Below (points)",
      suspensionDays: "Suspend (days)",
      lab: "Lab",
      blockedProgramPlaceholder: "e.g. a program that is not allowed",
      allLaboratoryRooms: "All laboratory rooms",
      active: "Active",
      disabled: "Disabled",
      users: "Users",
      backToAllRooms: "Back to all rooms",
      capacity: "Capacity",
      location: "Location",
      editLabInformation: "Edit lab information",
      labCode: "Lab code",
      labName: "Lab name",
      deleteLab: "Delete lab",
      saveChanges: "Save changes",
      disableLaboratory: "Disable this laboratory",
      enableLaboratory: "Enable this laboratory",
      suspendRoomBookings: "Suspend bookings for this room",
      allowRoomBookings: "Allow bookings for this room",
      disableAccess: "Disable access",
      enableAccess: "Enable access",
      classSchedules: "Class schedules",
      classSchedulesHint: "Time slots added here will be unavailable for user bookings",
      addClass: "Add class",
      createNewLab: "Create new lab",
      createLab: "Create lab",
      courseCode: "Course code",
      courseName: "Course name",
      instructorName: "Instructor name",
      dayOfWeek: "Day of week",
      timeSlot: "Time slot",
      semester: "Semester",
      academicYear: "Academic year",
      validFrom: "Valid from",
      validUntil: "Valid until",
      editClassSchedule: "Edit class schedule",
      addClassSchedule: "Add class schedule",
      cancelAction: "Cancel",
      createFailed: "Creation failed",
      updateFailed: "Update failed",
      updateSucceeded: "Updated successfully",
      deleteSucceeded: "Deleted successfully",
      deleteFailed: "Delete failed",
      missingRequiredFields: "Please complete all required fields",
      invalidScheduleDates: "The end date must not be earlier than the start date",
      operationFailed: "Operation failed",
      roleChanged: "User role updated successfully",
      roleNameSaved: "Role display name saved successfully",
      roleKeyInfo: "Role keys are internal identifiers and stay unchanged to protect sign-in and permissions. Display names and user assignments can still be edited.",
      roleDisplayNameInfo: "Role names are internal keys; display names can be customized for your organization.",
      allRolesSummary: "Total roles",
      usersWithRole: "Users with a role",
      systemRolesSummary: "System roles",
      pointRequestsCount: "requests",
      requestPoints: "Requested",
      requestSentAt: "Requested at",
      showing: "Showing",
      of: "of",
      banCriteriaDescription: "Set booking suspension duration by score level. A duration of 0 days disables suspension at that level.",
      banThresholdOrderWarning: "Thresholds must be ordered from lowest to highest, and the highest threshold must not exceed the minimum booking score.",
      testActionsFixedPolicy: "The test deduction and reset buttons use fixed values of -10 and 100 so they are not affected by the live policy.",
      pointEarnedTitle: "Points awarded",
      pointEarnedDescription: "Set the points users earn from normal activity",
      dailyBonusPolicy: "Daily bonus",
      dailyBonusPolicyHint: "Points awarded when the system starts a new day (0–10)",
      completeSessionPolicy: "Normal session completion",
      completeSessionPolicyHint: "Points awarded for ending a session normally (0–20)",
      pointDeductedTitle: "Points deducted",
      pointDeductedDescription: "Values must be zero or negative to prevent rule violations from awarding points",
      noShowPolicy: "No-show",
      noShowPolicyHint: "Deduct points when a booking expires without a check-in (-100 to 0)",
      forbiddenProgramPolicy: "Forbidden program use",
      forbiddenProgramPolicyHint: "Deduct points when the Agent detects a prohibited program (-100 to 0)",
      lateCancelPolicy: "Late cancellation",
      lateCancelPolicyHint: "Deduct points when a booking is cancelled shortly before it starts (-100 to 0)",
      recoveryAndBookingTitle: "Point recovery and booking access",
      recoveryAndBookingDescription: "Set the point recovery amount, warning threshold, and minimum score for booking",
      pointsReturnedOnApproval: "Points returned when a request is approved",
      pointsReturnedHint: "Number of points a user can request when their score reaches 0 (1–100)",
      warningThresholdLabel: "Warning threshold",
      warningThresholdHint: "Show a warning when the score is at or below this value (0–100)",
      banLevelOne: "Level 1 · Critical threshold",
      banLevelTwo: "Level 2 · Low score",
      banLevelThree: "Level 3 · Warning threshold",
      banLevelFour: "Level 4 · Below booking threshold",
      deleteTicketFailed: "An error occurred while updating the ticket status",
      ticketStatusUpdateFailed: "An error occurred while updating the ticket status",
      verifyUsersPending: "{count} users pending review",
      pointsPageDescription: "Review each account's accumulated points, today's points, and booking access",
      bookingDependsOnBan: "Booking access is determined by suspension status only",
      course: "Course",
      instructor: "Instructor",
      term: "Term",
      action: "Actions",
      weekdayMonday: "Monday",
      weekdayTuesday: "Tuesday",
      weekdayWednesday: "Wednesday",
      weekdayThursday: "Thursday",
      weekdayFriday: "Friday",
      weekdaySaturday: "Saturday",
      weekdaySunday: "Sunday",
      confirmDeleteLabPrefix: "Permanently delete lab",
      confirmDeleteLabSuffix: "All class schedules for this room will also be deleted. This action cannot be undone.",
      deleteScheduleConfirmation: "Are you sure you want to delete this schedule?",
      labCreated: "Lab created successfully",
      scheduleSaved: "Schedule saved successfully",
      pendingUsersLoadFailed: "Unable to load users awaiting review",
      verifyUserFailed: "Unable to process this user",
      rejectUserConfirmation: "Are you sure you want to reject and delete this user?",
      accountsInSystem: "Accounts in system",
      activeBans: "Active booking suspensions",
      noRoleAssigned: "No role assigned",
      appNameRequired: "Please enter a program name",
      blacklistOperationFailed: "Unable to update the blocked-program list",
      confirmRemoveBlacklistItem: "Remove from the blocked-program list",
      deleteBlacklistFailed: "Unable to remove this blocked-program entry",
      policyAdminLoginRequired: "Please sign in with an admin account to update point criteria",
      policySaveAdminLoginRequired: "Please sign in with an admin account to save point criteria",
      loadPolicyFailed: "Unable to load point criteria",
      savePolicyFailed: "Unable to save point criteria",
      policySaved: "Point criteria saved and will apply to future events",
      policyDefaultsRestored: "Form defaults restored. Save the criteria to apply them.",
      policyIntegerRequired: "Enter a whole number in every field",
      policyRangeInvalid: "One or more values are outside the allowed range",
      policyThresholdOrderInvalid: "Ban score thresholds must be unique and ordered from lowest to highest",
      adminLoginRequired: "Please sign in with an admin account to view user points",
      userDetailLoginRequired: "Please sign in with an admin account to view user details",
      pointRequestLoginRequired: "Please sign in with an admin account to manage point requests",
      testDeductionLoginRequired: "Please sign in with an admin account to test a point deduction",
      testResetLoginRequired: "Please sign in with an admin account to reset test points",
      loadUserPointsFailed: "Unable to load user points",
      loadUserDetailFailed: "Unable to load the user's details and history",
      pointRequestActionFailed: "Unable to process the point request",
      testDeductionFailed: "Unable to test the point deduction",
      testResetFailed: "Unable to reset test points",
      testDeductionConfirmPrefix: "Deduct 10 points from",
      testDeductionConfirmSuffix: "for testing?",
      testResetConfirmPrefix: "Reset the points for",
      testResetConfirmSuffix: "to 100 to start a new test?",
      userDetails: {
        bookings: "Bookings",
        sessions: "Sessions",
        programs: "Programs",
        pointHistory: "Point history",
        violations: "Violations",
        noBookingHistory: "No booking history yet",
        noBookingHistoryDescription: "This user has not created any room bookings",
        bookingDateTime: "Date and time",
        room: "Room",
        purpose: "Purpose",
        status: "Status",
        noSessions: "No session history yet",
        noSessionsDescription: "There is no room usage history for this user",
        checkInOut: "Check-in / check-out",
        deviceInUse: "Device used",
        endReason: "End reason",
        noProgramUsage: "No program usage history yet",
        noProgramUsageDescription: "The Agent has no program data from this user's sessions",
        time: "Time",
        program: "Program",
        duration: "Duration",
        device: "Device",
        noViolations: "No violations found",
        noViolationsDescription: "This user has no recorded program violations",
        detectedAt: "Detected at",
        evidence: "Evidence",
        actionTaken: "Action taken",
        noPointsHistory: "No point history yet",
        noPointsHistoryDescription: "No point changes have been recorded for this user",
        dateTime: "Date and time",
        reason: "Reason",
        pointChange: "Change",
        pointsAfter: "Points after change",
        dailyPoints: "Daily points",
        dailyPointsLimit: "Showing up to 100 entries",
        noDailyPoints: "No daily scores yet",
        accountDetails: "Account details",
        accountStatusAndUsage: "Points and usage status",
        studentId: "Student ID",
        faculty: "Faculty",
        department: "Department",
        createdAt: "Created at",
        bookingAccess: "Booking access",
        historySummary: "History summary",
        accountUsable: "Account active",
        awaitingReview: "Pending review",
        noRoom: "Room not specified",
        noDevice: "Device not specified",
        noMac: "MAC not specified",
        noReason: "Reason not specified",
        noProgram: "Not specified",
        noProcess: "Process not specified",
        noDetails: "No additional details",
        event: "Event",
        recordedEvent: "Event recorded",
        noData: "No data available",
        until: "until",
        seconds: "seconds",
        minutes: "minutes",
        bookingReserved: "Reserved",
        bookingAttended: "Attended",
        bookingCompleted: "Completed",
        bookingCancelled: "Cancelled",
        bookingNoShow: "No-show",
        sessionActive: "In use",
        sessionCompleted: "Completed normally",
        sessionAbandoned: "Connection lost",
        roleStudent: "Student",
        roleGuest: "Guest",
        roleUser: "User",
        roleAdministrator: "Administrator",
        roleSystemAdmin: "System Admin",
        pointDailyBonus: "Daily bonus",
        pointNoShow: "No-show",
        pointForbiddenProgram: "Forbidden program use",
        pointLateCancel: "Late cancellation",
        pointSessionComplete: "Session completed normally",
        pointAdminGrant: "Administrator point adjustment",
        pointAdjustment: "Point adjustment",
      },
    },
  },
};

function getInitialLanguage() {
  if (typeof window === "undefined") return "th";
  const storedLanguage = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return storedLanguage === "en" || storedLanguage === "th" ? storedLanguage : "th";
}

function readMessage(language, key) {
  return key.split(".").reduce((value, segment) => value?.[segment], messages[language]);
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    document.documentElement.lang = language;
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  }, [language]);

  const value = useMemo(() => ({
    language,
    isEnglish: language === "en",
    setLanguage,
    toggleLanguage: () => setLanguage((current) => (current === "th" ? "en" : "th")),
    t: (key, fallback) => readMessage(language, key) ?? readMessage("th", key) ?? fallback ?? key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
