import { useEffect, useMemo, useState } from "react";
import { LanguageContext } from "./language-context.js";

const LANGUAGE_STORAGE_KEY = "smart-lab-language";

const messages = {
  th: {
    language: {
      switchTo: "English",
      current: "ภาษาไทย",
      aria: "เปลี่ยนภาษาเป็นภาษาอังกฤษ",
    },
    common: {
      labReserve: "จองห้อง Lab",
      reserved: "รายการจอง",
      history: "ประวัติการจอง",
      myTickets: "ตั๋วของฉัน",
      support: "ช่วยเหลือ",
      notifications: "การแจ้งเตือน",
      noNotifications: "ยังไม่มีการแจ้งเตือน",
      systemAdmin: "ผู้ดูแลระบบ",
      administrator: "ผู้ดูแลระบบ",
      profile: "โปรไฟล์",
      manageAccount: "จัดการบัญชี",
      guestUser: "ผู้ใช้ Guest",
      login: "เข้าสู่ระบบ",
      settings: "ตั้งค่า",
      logout: "ออกจากระบบ",
      search: "ค้นหา...",
      refresh: "รีเฟรชข้อมูล",
      save: "บันทึก",
      cancel: "ยกเลิก",
      close: "ปิด",
      edit: "แก้ไข",
      delete: "ลบ",
      add: "เพิ่ม",
      loading: "กำลังโหลด...",
      noData: "ยังไม่มีข้อมูล",
      details: "รายละเอียด",
      status: "สถานะ",
      active: "ใช้งานอยู่",
      inactive: "ไม่ได้ใช้งาน",
      approved: "อนุมัติแล้ว",
      pending: "รอดำเนินการ",
      completed: "เสร็จสิ้น",
      failed: "ไม่สำเร็จ",
      all: "ทั้งหมด",
      today: "วันนี้",
      date: "วันที่",
      time: "เวลา",
      user: "ผู้ใช้",
      role: "Role",
      email: "อีเมล",
      phone: "เบอร์โทรศัพท์",
      points: "คะแนน",
      locale: "th-TH",
      bannedUntil: "บัญชีถูกระงับการจองถึง",
      requiredFields: "กรุณากรอกข้อมูลให้ครบถ้วน",
      loginBeforeSupport: "กรุณาเข้าสู่ระบบก่อนส่งคำร้อง",
      ticketSent: "ส่ง Ticket ให้ผู้ดูแลระบบเรียบร้อยแล้ว",
      error: "เกิดข้อผิดพลาด",
      contactSupport: "แจ้งปัญหาถึงผู้ดูแลระบบ",
      sending: "กำลังส่ง...",
      sendTicket: "ส่ง Ticket",
      actions: "จัดการ",
      yes: "ใช่",
      no: "ไม่ใช่",
      back: "ย้อนกลับ",
      next: "ถัดไป",
      confirm: "ยืนยัน",
      openMenu: "เปิดเมนูผู้ดูแลระบบ",
      closeMenu: "ปิดเมนู",
      noSignal: "ยังไม่พบสัญญาณ",
      noMac: "ไม่มี MAC",
      source: "ต้นฉบับ",
      maintenance: "บำรุงรักษา",
      revoked: "ยกเลิกสิทธิ์",
      minutes: "นาที",
      day: "วัน",
      allRoles: "ทุก Role",
    },
    user: {
      pageTitle: "จองห้อง Lab",
      searchRooms: "ค้นหาด้วยรหัส ชื่อ หรือสถานที่...",
      noLabs: "ยังไม่มีห้อง Lab ที่พร้อมให้บริการ",
      selectRoom: "เลือกห้อง Lab",
      selectDate: "เลือกวันที่",
      selectTime: "เลือกเวลา",
      bookingHistory: "ประวัติการจอง",
      pastReservations: "รายการจองที่ผ่านมา",
      noHistory: "ไม่พบประวัติการจอง",
      reservedTitle: "รายการจองของฉัน",
      noReservations: "ยังไม่มีรายการจอง",
      profileTitle: "โปรไฟล์ของฉัน",
      ticketTitle: "ตั๋วของฉัน",
      noTickets: "ยังไม่มีตั๋ว",
      notifications: "การแจ้งเตือน",
      booking: "จองห้อง",
      bookingSuccess: "จองห้องสำเร็จ",
      confirmBooking: "ยืนยันการจอง",
      cancelBooking: "ยกเลิกการจอง",
      room: "ห้อง",
      lab: "Lab",
      duration: "ระยะเวลา",
      startTime: "เวลาเริ่มต้น",
      endTime: "เวลาสิ้นสุด",
      points: "คะแนน",
      todayPoints: "คะแนนวันนี้",
      permission: "สิทธิ์การจอง",
      searchResults: "ผลการค้นหา",
      selectLabRoom: "เลือกห้อง Lab",
      available: "พร้อมใช้งาน",
      maintenance: "ปิดปรับปรุง",
      users: "ผู้ใช้",
      location: "สถานที่",
      noLabsMatching: "ไม่พบห้อง Lab ที่ตรงกับ",
      adjustSearch: "ลองปรับคำค้นหาใหม่",
      clearSearch: "ล้างการค้นหา",
      backToRooms: "กลับไปยังรายการห้องทั้งหมด",
      capacity: "ความจุ",
      advanceBooking: "จองล่วงหน้าได้ไม่เกิน 2 วัน",
      requiresNotice: "ต้องจองล่วงหน้าอย่างน้อย 2 ชั่วโมง",
      reservedForClass: "สงวนไว้สำหรับชั้นเรียน",
      fullyBooked: "เต็มแล้ว",
      tooClose: "ใกล้เกินไป (ต้องรอ 2 ชั่วโมง)",
      timePassed: "เวลาผ่านไปแล้ว",
      seatsLeft: "ที่นั่งคงเหลือ",
      confirmYourBooking: "ยืนยันการจองของคุณ",
      yourSelection: "รายการที่เลือก",
      loginToBook: "เข้าสู่ระบบเพื่อจอง",
      bookingConfirmed: "ยืนยันการจองสำเร็จ!",
      reservationConfirmed: "การจองห้องของคุณได้รับการยืนยันแล้ว",
      gotIt: "รับทราบ ขอบคุณ",
      reservedStatus: "สถานะการจอง",
      noUpcomingReservations: "ไม่พบรายการจองที่กำลังจะมาถึง",
      cancelReservation: "ยกเลิกการจอง",
      cancelReservationConfirm: "คุณแน่ใจหรือไม่ว่าต้องการยกเลิกการจองนี้ การดำเนินการนี้ไม่สามารถย้อนกลับได้",
      keepReservation: "เก็บรายการจองไว้",
      yesCancel: "ใช่ ยกเลิก",
      pendingCheckIn: "รอยืนยันการเข้าใช้งาน",
      inUse: "กำลังใช้งาน",
      sessionCompleted: "ใช้งานเสร็จแล้ว",
      noShow: "ไม่มาตามการจอง",
      cancelled: "ยกเลิกแล้ว",
      myRequests: "คำร้องของฉัน",
      trackRequests: "ติดตามสถานะคำร้องที่ส่งถึงผู้ดูแลระบบ",
      requests: "คำร้อง",
      requestHistory: "ประวัติคำร้อง",
      requestConversation: "รายการสนทนาและการติดตามปัญหาของคุณ",
      noTicketsSent: "คุณยังไม่เคยส่งคำร้อง",
      supportHelp: "หากพบปัญหา สามารถกดช่วยเหลือจากเมนูด้านซ้ายได้",
      subject: "หัวข้อ",
      message: "รายละเอียด",
      submittedAt: "วันที่ส่ง",
      unknownStatus: "ไม่ทราบสถานะ",
      openTicket: "รอดำเนินการ",
      inProgressTicket: "กำลังดำเนินการ",
      closedTicket: "ดำเนินการเสร็จสิ้น",
      joinedAt: "เข้าร่วมเมื่อ",
      usageStats: "สถิติการใช้งาน",
      bookings: "การจอง",
      personalInfo: "ข้อมูลส่วนตัว",
      studentId: "รหัสนักศึกษา",
      facultyDepartment: "คณะ / สาขา",
      currentPoints: "คะแนนปัจจุบัน",
      myPoints: "คะแนนของฉัน",
      scoreHistory: "ประวัติการเปลี่ยนคะแนน",
      noScoreHistory: "ยังไม่มีประวัติการเปลี่ยนคะแนน",
      statusNormal: "สถานะปกติ",
      lowPointsWarning: "คะแนนต่ำ — โปรดระวังการทำผิดกฎ",
      pointsStatusUnavailable: "ยังตรวจสอบสถานะไม่ได้",
      pointRequestPending: "ส่งคำขอเพิ่มคะแนนแล้ว — รอ Admin พิจารณา",
      zeroPointsMessage: "คะแนนของคุณเหลือ 0 คะแนน กรุณาติดต่อ Admin เพื่อขอความช่วยเหลือ",
      contactAdmin: "ติดต่อ Admin เพื่อขอเพิ่ม",
      sendingRequest: "กำลังส่งคำขอ...",
      requestSubmitted: "คะแนนแล้ว กรุณารอ Admin พิจารณา",
    },
    admin: {
      dashboard: "แดชบอร์ด",
      manageLabs: "จัดการ Lab",
      labDevices: "เครื่องประจำ Lab",
      verifyUsers: "ตรวจสอบผู้ใช้",
      userPoints: "คะแนนผู้ใช้",
      pointCriteria: "เกณฑ์คะแนน",
      roleManagement: "จัดการ Role",
      blacklist: "Blacklist",
      ticket: "Ticket",
      dashboardTitle: "แดชบอร์ดผู้ดูแลระบบ",
      manageLabsTitle: "จัดการห้อง Lab",
      devicesTitle: "เครื่องประจำ Lab",
      verifyTitle: "ตรวจสอบผู้ใช้ Guest",
      pointsTitle: "คะแนนของผู้ใช้ทั้งหมด",
      policyTitle: "ปรับเกณฑ์คะแนน",
      rolesTitle: "จัดการบทบาทผู้ใช้งาน",
      blacklistTitle: "จัดการรายการโปรแกรมต้องห้าม",
      ticketTitle: "จัดการ Ticket",
      totalRequests: "คำขอทั้งหมด",
      activeUsers: "ผู้ใช้งานอยู่",
      pendingUsersCard: "ผู้ใช้ที่รอตรวจสอบ",
      supportTickets: "Support Tickets",
      recentReservations: "รายการจองล่าสุด",
      noRecentReservations: "ไม่พบรายการจองล่าสุด",
      searchLabs: "ค้นหา Lab...",
      searchUsers: "ค้นหาชื่อ อีเมล หรือ User ID...",
      searchPendingUsers: "ค้นหาผู้ใช้ที่รอตรวจสอบ...",
      addLab: "เพิ่ม Lab ใหม่",
      registerDevice: "สร้างรหัสลงทะเบียน",
      pendingUsers: "รอตรวจสอบ",
      allUsers: "ผู้ใช้ทั้งหมด",
      averagePoints: "คะแนนเฉลี่ย",
      belowThreshold: "ต่ำกว่าเกณฑ์",
      bannedUsers: "ถูกระงับการจอง",
      pointRequests: "คำขอเพิ่มแต้ม",
      noPendingUsers: "ไม่มีผู้ใช้ที่รอการตรวจสอบ",
      noRoles: "ยังไม่มีข้อมูล Role",
      noBlacklist: "ยังไม่มีโปรแกรมต้องห้าม",
      noDevices: "ยังไม่มีเครื่องที่ลงทะเบียน",
      deviceHeading: "เครื่องประจำ Lab",
      deviceSubtitle: "ลงทะเบียนและควบคุมว่าเครื่องใดอยู่ใน Lab ใด",
      createEnrollment: "สร้างรหัสลงทะเบียน",
      machine: "เครื่อง",
      agent: "Agent",
      lastSignal: "สัญญาณล่าสุด",
      manage: "การจัดการ",
      saveDevice: "บันทึก",
      savingDevice: "กำลังบันทึก",
      enrollmentTitle: "สร้างรหัสลงทะเบียนเครื่อง",
      enrollmentAge: "อายุรหัส",
      oneTimeCode: "รหัสนี้ใช้ได้ครั้งเดียว ใช้สำหรับลงทะเบียนเครื่องหนึ่งเครื่องเท่านั้น",
      generatedFor: "สร้างรหัสสำหรับ",
      copyCode: "คัดลอกรหัส",
      copied: "คัดลอกรหัสแล้ว",
      copyFailed: "คัดลอกรหัสไม่สำเร็จ กรุณาคัดลอกด้วยตนเอง",
      expiresAt: "หมดอายุ",
      setupCommand: "จากนั้นให้รันคำสั่ง provision_device บนเครื่องเป้าหมาย",
      createCode: "สร้างรหัส",
      deviceRegistered: "บันทึกการตั้งค่าเครื่องแล้ว",
      chooseLabFirst: "กรุณาเลือก Lab ก่อนสร้างรหัส",
      enrollmentFailed: "สร้างรหัสลงทะเบียนไม่สำเร็จ",
      deviceSaveFailed: "บันทึกข้อมูลไม่สำเร็จ",
      labsHeading: "จัดการห้อง Lab",
      labsSubtitle: "สร้าง แก้ไข และกำหนดตารางการใช้งานห้อง Lab",
      rolesHeading: "จัดการบทบาทผู้ใช้งาน",
      rolesSubtitle: "กำหนดสิทธิ์และบทบาทให้กับผู้ใช้งานในระบบ",
      rolesInSystem: "Roles ในระบบ",
      assignRole: "กำหนด Role ให้ User",
      roleDisplayName: "ชื่อแสดงผล",
      roleUsers: "ผู้ใช้งาน",
      roleType: "ประเภท",
      editRoleTitle: "แก้ไขชื่อแสดงผล Role",
      roleKey: "Role key",
      cannotChangeSelf: "ไม่สามารถเปลี่ยน Role ตัวเอง",
      noMatchingUsers: "ไม่พบ User ตามเงื่อนไขที่เลือก",
      verifyHeading: "ตรวจสอบผู้ใช้ Guest",
      verifySubtitle: "ตรวจสอบและอนุมัติผู้ใช้ภายนอกก่อนให้สามารถจองห้อง Lab ได้",
      noPendingVerifications: "ไม่มีผู้ใช้ที่รอตรวจสอบ",
      allGuestsUpToDate: "บัญชี Guest ทั้งหมดได้รับการตรวจสอบแล้ว",
      noMatchingGuestUsers: "ไม่พบผู้ใช้ที่ตรงกัน",
      adjustGuestSearch: "ลองค้นหาด้วยชื่อ อีเมล หรือเบอร์โทรศัพท์อื่น",
      guestUser: "ผู้ใช้ Guest",
      pending: "รอดำเนินการ",
      reject: "ปฏิเสธ",
      approve: "อนุมัติ",
      saving: "กำลังบันทึก...",
      userPointsHeading: "คะแนนของผู้ใช้ทั้งหมด",
      pointSummaryDate: "คะแนนรายวัน ณ",
      pointFilter: "ตัวกรอง",
      pointSort: "เรียงตาม",
      allUsersFilter: "ผู้ใช้ทั้งหมด",
      lowPoints: "คะแนนต่ำ",
      bookingBanned: "ถูกระงับการจอง",
      bookingAllowed: "จองได้",
      pointsAscending: "คะแนนน้อยไปมาก",
      pointsDescending: "คะแนนมากไปน้อย",
      userNameSort: "ชื่อผู้ใช้",
      accumulatedPoints: "คะแนนสะสม",
      dailyPoints: "คะแนนวันนี้",
      bookingRights: "สิทธิ์การจอง",
      lastUpdated: "อัปเดตล่าสุด",
      blockedProgramHeading: "จัดการรายการโปรแกรมต้องห้าม",
      blockedProgramSubtitle: "โปรแกรมที่ Agent จะตรวจพบและแจ้งเตือนตามนโยบายของ Lab",
      addBlockedProgram: "เพิ่มโปรแกรมต้องห้าม",
      programName: "ชื่อโปรแกรม",
      description: "รายละเอียด",
      editProgram: "แก้ไขโปรแกรม",
      addProgram: "เพิ่มโปรแกรม",
      noBlockedPrograms: "ยังไม่มีโปรแกรมต้องห้าม",
      pointPolicyHeading: "ปรับเกณฑ์คะแนน",
      pointPolicySubtitle: "ตั้งค่าคะแนนที่ใช้กับการตรวจจับ การจบ Session การแจ้งเตือน และสิทธิ์การจองของผู้ใช้",
      pointPolicyInfo: "ค่าใหม่จะมีผลกับเหตุการณ์คะแนนและการตรวจสอบสิทธิ์การจองในครั้งถัดไป ประวัติคะแนนเดิมจะไม่ถูกแก้ไข",
      refreshData: "รีเฟรชข้อมูล",
      restoreDefaults: "คืนค่าเริ่มต้นในฟอร์ม",
      savePolicy: "บันทึกเกณฑ์คะแนน",
      bookingBanCriteria: "เกณฑ์การระงับการจอง",
      policyScope: "ขอบเขตของการตั้งค่า",
      ticketId: "ID",
      ticketUserId: "User ID",
      ticketSubject: "หัวข้อ",
      ticketMessage: "รายละเอียด",
      ticketSubmitted: "วันที่ส่ง",
      ticketStatus: "สถานะ",
      ticketManage: "จัดการ",
    },
  },
  en: {
    language: {
      switchTo: "ภาษาไทย",
      current: "English",
      aria: "Change language to Thai",
    },
    common: {
      labReserve: "Lab Reserve",
      reserved: "Reserved",
      history: "History",
      myTickets: "My Tickets",
      support: "Support",
      notifications: "Notifications",
      noNotifications: "No notifications yet",
      systemAdmin: "System Admin",
      administrator: "Administrator",
      profile: "Profile",
      manageAccount: "Manage your account",
      guestUser: "Guest User",
      login: "Log in",
      settings: "Settings",
      logout: "Log out",
      search: "Search...",
      refresh: "Refresh",
      save: "Save",
      cancel: "Cancel",
      close: "Close",
      edit: "Edit",
      delete: "Delete",
      add: "Add",
      loading: "Loading...",
      noData: "No data available",
      details: "Details",
      status: "Status",
      active: "Active",
      inactive: "Inactive",
      approved: "Approved",
      pending: "Pending",
      completed: "Completed",
      failed: "Failed",
      all: "All",
      today: "Today",
      date: "Date",
      time: "Time",
      user: "User",
      role: "Role",
      email: "Email",
      phone: "Phone",
      points: "points",
      locale: "en-GB",
      bannedUntil: "Booking is suspended until",
      requiredFields: "Please complete all fields",
      loginBeforeSupport: "Please log in before sending a request",
      ticketSent: "Ticket sent to the administrator",
      error: "Error",
      contactSupport: "Contact the administrator",
      sending: "Sending...",
      sendTicket: "Send ticket",
      actions: "Actions",
      yes: "Yes",
      no: "No",
      back: "Back",
      next: "Next",
      confirm: "Confirm",
      openMenu: "Open admin menu",
      closeMenu: "Close menu",
      noSignal: "No signal yet",
      noMac: "No MAC",
      source: "Source",
      maintenance: "Maintenance",
      revoked: "Revoked",
      minutes: "minutes",
      day: "days",
      allRoles: "All roles",
    },
    user: {
      pageTitle: "Lab Reserve",
      searchRooms: "Search by code, name, or location...",
      noLabs: "No labs are currently available",
      selectRoom: "Select a lab",
      selectDate: "Select a date",
      selectTime: "Select a time",
      bookingHistory: "Booking History",
      pastReservations: "Past Reservations",
      noHistory: "No booking history found",
      reservedTitle: "My Reservations",
      noReservations: "No reservations yet",
      profileTitle: "My Profile",
      ticketTitle: "My Tickets",
      noTickets: "No tickets yet",
      notifications: "Notifications",
      booking: "Book a lab",
      bookingSuccess: "Booking created successfully",
      confirmBooking: "Confirm booking",
      cancelBooking: "Cancel booking",
      room: "Room",
      lab: "Lab",
      duration: "Duration",
      startTime: "Start time",
      endTime: "End time",
      points: "Points",
      todayPoints: "Today's points",
      permission: "Booking access",
      searchResults: "Search results",
      selectLabRoom: "Select a lab room",
      available: "Available",
      maintenance: "Maintenance",
      users: "Users",
      location: "Location",
      noLabsMatching: "No labs found matching",
      adjustSearch: "Try adjusting your search keywords.",
      clearSearch: "Clear search",
      backToRooms: "Back to all rooms",
      capacity: "Capacity",
      advanceBooking: "Advance booking up to 2 days",
      requiresNotice: "Requires 2 hours advance notice",
      reservedForClass: "Reserved for class",
      fullyBooked: "Fully booked",
      tooClose: "Too close (wait 2 hours)",
      timePassed: "Time passed",
      seatsLeft: "Seats left",
      confirmYourBooking: "Confirm your booking",
      yourSelection: "Your selection",
      loginToBook: "Log in to book",
      bookingConfirmed: "Booking confirmed!",
      reservationConfirmed: "Your lab reservation has been confirmed.",
      gotIt: "Got it, thanks",
      reservedStatus: "Reservation status",
      noUpcomingReservations: "No upcoming reservations found",
      cancelReservation: "Cancel Reservation",
      cancelReservationConfirm: "Are you sure you want to cancel this booking? This action cannot be undone.",
      keepReservation: "Keep it",
      yesCancel: "Yes, cancel",
      pendingCheckIn: "Awaiting check-in",
      inUse: "In use",
      sessionCompleted: "Completed",
      noShow: "No-show",
      cancelled: "Cancelled",
      myRequests: "My requests",
      trackRequests: "Track requests sent to the administrator",
      requests: "requests",
      requestHistory: "Request history",
      requestConversation: "Conversations and updates for your requests",
      noTicketsSent: "You have not sent any requests",
      supportHelp: "If you need help, use Support in the left menu",
      subject: "Subject",
      message: "Message",
      submittedAt: "Submitted",
      unknownStatus: "Unknown status",
      openTicket: "Open",
      inProgressTicket: "In progress",
      closedTicket: "Resolved",
      joinedAt: "Joined",
      usageStats: "Usage statistics",
      bookings: "Bookings",
      personalInfo: "Personal information",
      studentId: "Student ID",
      facultyDepartment: "Faculty / Department",
      currentPoints: "Current points",
      myPoints: "My points",
      scoreHistory: "Point history",
      noScoreHistory: "No point history yet",
      statusNormal: "Status: normal",
      lowPointsWarning: "Low points — please follow the lab rules",
      pointsStatusUnavailable: "Point status unavailable",
      pointRequestPending: "Point request sent — waiting for admin review",
      zeroPointsMessage: "You have 0 points. Contact an admin for assistance.",
      contactAdmin: "Contact admin to request",
      sendingRequest: "Sending request...",
      requestSubmitted: "points. Please wait for admin review",
    },
    admin: {
      dashboard: "Dashboard",
      manageLabs: "Manage Labs",
      labDevices: "Lab Devices",
      verifyUsers: "Verify Users",
      userPoints: "User Points",
      pointCriteria: "Point Criteria",
      roleManagement: "Role Management",
      blacklist: "Blacklist",
      ticket: "Ticket",
      dashboardTitle: "Admin Dashboard",
      manageLabsTitle: "Manage Laboratory Rooms",
      devicesTitle: "Lab Devices",
      verifyTitle: "Verify Guest Users",
      pointsTitle: "All User Points",
      policyTitle: "Point Criteria",
      rolesTitle: "Role Management",
      blacklistTitle: "Blocked Programs",
      ticketTitle: "Ticket Manager",
      totalRequests: "Total requests",
      activeUsers: "Active users",
      pendingUsersCard: "Pending users",
      supportTickets: "Support tickets",
      recentReservations: "Recent reservations",
      noRecentReservations: "No recent reservations found",
      searchLabs: "Search labs...",
      searchUsers: "Search name, email, or User ID...",
      searchPendingUsers: "Search pending users...",
      addLab: "Add New Lab",
      registerDevice: "Create registration code",
      pendingUsers: "Pending review",
      allUsers: "All users",
      averagePoints: "Average points",
      belowThreshold: "Below threshold",
      bannedUsers: "Booking bans",
      pointRequests: "Point requests",
      noPendingUsers: "No users are waiting for review",
      noRoles: "No roles found",
      noBlacklist: "No blocked programs",
      noDevices: "No registered devices",
      deviceHeading: "Lab Devices",
      deviceSubtitle: "Register devices and control which lab they belong to",
      createEnrollment: "Create registration code",
      machine: "Device",
      agent: "Agent",
      lastSignal: "Last signal",
      manage: "Actions",
      saveDevice: "Save",
      savingDevice: "Saving...",
      enrollmentTitle: "Create device registration code",
      enrollmentAge: "Code lifetime",
      oneTimeCode: "This code can be used once to register one device.",
      generatedFor: "Code created for",
      copyCode: "Copy code",
      copied: "Code copied",
      copyFailed: "Could not copy the code. Please copy it manually.",
      expiresAt: "Expires",
      setupCommand: "Then run the provision_device command on the target device",
      createCode: "Create code",
      deviceRegistered: "Device settings saved",
      chooseLabFirst: "Select a lab before creating a code",
      enrollmentFailed: "Could not create the registration code",
      deviceSaveFailed: "Could not save the device",
      labsHeading: "Manage Laboratory Rooms",
      labsSubtitle: "Create, edit, and configure lab room schedules",
      rolesHeading: "Role Management",
      rolesSubtitle: "Manage access roles and permissions for system users",
      rolesInSystem: "Roles in the system",
      assignRole: "Assign role to users",
      roleDisplayName: "Display name",
      roleUsers: "Users",
      roleType: "Type",
      editRoleTitle: "Edit role display name",
      roleKey: "Role key",
      cannotChangeSelf: "You cannot change your own role",
      noMatchingUsers: "No users match the selected filters",
      verifyHeading: "Verify Guest Users",
      verifySubtitle: "Review and approve external users before they can book labs.",
      noPendingVerifications: "No pending verifications",
      allGuestsUpToDate: "All guest accounts are up to date.",
      noMatchingGuestUsers: "No matching users",
      adjustGuestSearch: "Try another name, email, or phone number",
      guestUser: "Guest User",
      pending: "Pending",
      reject: "Reject",
      approve: "Approve",
      saving: "Saving...",
      userPointsHeading: "All User Points",
      pointSummaryDate: "Daily points as of",
      pointFilter: "Filter",
      pointSort: "Sort by",
      allUsersFilter: "All users",
      lowPoints: "Low points",
      bookingBanned: "Booking banned",
      bookingAllowed: "Booking allowed",
      pointsAscending: "Points: low to high",
      pointsDescending: "Points: high to low",
      userNameSort: "User name",
      accumulatedPoints: "Accumulated points",
      dailyPoints: "Today's points",
      bookingRights: "Booking access",
      lastUpdated: "Last updated",
      blockedProgramHeading: "Blocked Programs",
      blockedProgramSubtitle: "Programs that the Agent detects and handles according to lab policy",
      addBlockedProgram: "Add blocked program",
      programName: "Program name",
      description: "Description",
      editProgram: "Edit program",
      addProgram: "Add program",
      noBlockedPrograms: "No blocked programs",
      pointPolicyHeading: "Point Criteria",
      pointPolicySubtitle: "Configure points used for detection, session completion, alerts, and booking access",
      pointPolicyInfo: "New values apply to future point events and booking access checks. Existing point history is not changed.",
      refreshData: "Refresh data",
      restoreDefaults: "Restore form defaults",
      savePolicy: "Save point criteria",
      bookingBanCriteria: "Booking suspension criteria",
      policyScope: "Configuration scope",
      ticketId: "ID",
      ticketUserId: "User ID",
      ticketSubject: "Subject",
      ticketMessage: "Message",
      ticketSubmitted: "Submitted",
      ticketStatus: "Status",
      ticketManage: "Actions",
    },
  },
};

function getInitialLanguage() {
  if (typeof window === "undefined") return "th";
  const storedLanguage = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return storedLanguage === "en" || storedLanguage === "th" ? storedLanguage : "th";
}

function readMessage(language, key) {
  return key.split(".").reduce((value, segment) => value?.[segment], messages[language]);
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    document.documentElement.lang = language;
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  }, [language]);

  const value = useMemo(() => ({
    language,
    isEnglish: language === "en",
    setLanguage,
    toggleLanguage: () => setLanguage((current) => (current === "th" ? "en" : "th")),
    t: (key, fallback = key) => readMessage(language, key) || fallback,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
