"""One-time source provisioning utility for a Smart Lab workstation.

An administrator creates an enrollment code in the Admin website first. This
script exchanges that short-lived code for a device credential and stores it
next to the Agent's local outbox. It intentionally does not expose a list of
Labs for a workstation user to choose from.
"""

from __future__ import annotations

import argparse
import os
import platform
import sys
import uuid

import requests

from agent_device import load_device_registration, save_device_registration


DEFAULT_API_URL = "https://h0sh1na-smart-lab-backend.hf.space"


def _response_detail(response: requests.Response) -> str:
    try:
        payload = response.json()
    except ValueError:
        return response.text.strip()[:300]
    if isinstance(payload, dict):
        return str(payload.get("detail") or payload.get("message") or "").strip()
    return ""


def _device_mac() -> str:
    return ":".join(f"{byte:02x}" for byte in uuid.getnode().to_bytes(6, "big"))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Register this Windows workstation to a Lab using an Admin enrollment code.",
    )
    parser.add_argument(
        "--api-url",
        default=os.getenv("SMART_LAB_API_URL", DEFAULT_API_URL),
        help="Smart Lab Backend URL",
    )
    parser.add_argument(
        "--enrollment-code",
        help="One-time code generated by the Admin website",
    )
    parser.add_argument(
        "--device-name",
        default=platform.node() or "Smart Lab workstation",
        help="Display name for this workstation",
    )
    parser.add_argument(
        "--device-id",
        help="Optional existing device id; by default the saved id is reused",
    )
    parser.add_argument(
        "--agent-version",
        default=os.getenv("SMART_LAB_AGENT_VERSION", "source"),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    enrollment_code = (args.enrollment_code or input("Enrollment code: ")).strip()
    if not enrollment_code:
        print("Enrollment code is required.", file=sys.stderr)
        return 2

    saved = load_device_registration() or {}
    device_id = (
        (args.device_id or "").strip()
        or str(saved.get("device_id") or "").strip()
        or uuid.uuid4().hex
    )
    api_url = args.api_url.rstrip("/")
    payload = {
        "enrollment_code": enrollment_code,
        "device_id": device_id,
        "device_name": args.device_name.strip() or platform.node(),
        "device_mac": _device_mac(),
        "agent_version": args.agent_version.strip()[:64] or "source",
    }

    try:
        response = requests.post(
            f"{api_url}/agent/register-device",
            data=payload,
            timeout=20,
        )
    except requests.RequestException as exc:
        print(f"Could not connect to Backend: {exc}", file=sys.stderr)
        return 1

    if response.status_code not in {200, 201}:
        detail = _response_detail(response) or f"HTTP {response.status_code}"
        print(f"Device registration failed: {detail}", file=sys.stderr)
        return 1

    result = response.json()
    device = result.get("device") or {}
    lab = device.get("lab") or {}
    registration = {
        "device_id": result.get("device_id") or device_id,
        "device_token": result.get("device_token"),
        "lab_id": lab.get("id"),
        "lab_code": lab.get("code"),
        "lab_name": lab.get("name"),
        "device_name": device.get("device_name") or payload["device_name"],
        "device_mac": device.get("device_mac") or payload["device_mac"],
        "agent_version": device.get("agent_version") or payload["agent_version"],
        "registered_at": device.get("created_at"),
    }
    path = save_device_registration(registration)
    print("Device registered successfully.")
    print(f"Lab: {registration['lab_code']} - {registration['lab_name']}")
    print(f"Device ID: {registration['device_id']}")
    print(f"Saved registration: {path}")
    print("Restart Smart Lab Agent before starting the next user session.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
